In [31]:
import torch
import numpy as np

In [29]:
print(torch.__version__)

2.9.1+cu128


In [30]:
print(torch.cuda.is_available())

True


In [ ]:
tensor0d = torch.tensor(1)
tensor1d = torch.tensor([1,2,3])
tensor2d = torch.tensor([[1,2], 
                         [3,4]])
tensor3d_1 = torch.tensor([[[1, 2], [3, 4]], 
                           [[5, 6], [7, 8]]])
ary3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
tensor3d_2 = torch.tensor(ary3d) # Copies mumpy array
tensor3d_3 = torch.from_numpy(ary3d) # Shares memory with NumPy array

In [48]:
ary3d[0, 0, 0] = 999
print(tensor3d_2) # remains unchnaged
print(tensor3d_3) # changes because of memory sharing

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
tensor([[[999,   2],
         [  3,   4]],

        [[  5,   6],
         [  7,   8]]])


---

In [49]:
tensor1d = torch.tensor([1, 2, 3])
print(tensor1d.dtype)

torch.int64


In [50]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
print(floatvec.dtype)

torch.float32


In [51]:
floatvec = tensor1d.to(torch.float32)
print(floatvec.dtype)

torch.float32


---

In [52]:
tensor2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [53]:
tensor2d.shape

torch.Size([2, 3])

In [54]:
tensor2d.reshape(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [55]:
tensor2d.view(3, 2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [56]:
tensor2d.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [57]:
tensor2d.matmul(tensor2d.T)

tensor([[14, 32],
        [32, 77]])

In [58]:
tensor2d @ tensor2d.T

tensor([[14, 32],
        [32, 77]])

---

In [59]:
import torch.nn.functional as F

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2])
b = torch.tensor([0.0])

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)
print(loss)

tensor(0.0852)


---

In [60]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2], requires_grad=True)
b = torch.tensor([0.0], requires_grad=True)

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

grad_L_w1 = grad(loss, w1, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

print(grad_L_w1)
print(grad_L_b)

(tensor([-0.0898]),)
(tensor([-0.0817]),)


In [61]:
loss.backward()

print(w1.grad)
print(b.grad)

tensor([-0.0898])
tensor([-0.0817])


---

In [ ]:
class NeuralNetwork(torch.nn.Module)